### ISSUE TITLE
Rendering problem with "inline" divisions

### ISSUE THREAD

**Issue by javila** [Proektsoftbg/Calcpad#687]
Hi there!

The output rendering of "inline" divisions (using `÷` character) needs some attention. Maybe there should be a way to preserve input parentheses...

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/28219420-8d06-4244-8571-4f3377b3e3d1" />

An option could be: typing something between double parentheses should force the rendering of a parenthesis. It would be quite useful when we want a bit more control over the output...

`a÷((b÷c))` --> `a/(b/c)`

**Comment by Proektsoftbg** [comment]
Thank you for bringing another valuable feedback. Yes, it was a bug. I fixed this too and updated the source code.

<img width="1778" height="1069" alt="Image" src="https://github.com/user-attachments/assets/429b9384-e217-443a-bcda-bcdd77aff150" />

There was one more fix just now after your last comment and now I think everything is fine. I will close this issue but you can reopen it anything else appears. Thank you once again for your kind help and contribution.

**Comment by Proektsoftbg** [comment]
Hi! Thank you very much for reporting this. 

I think I fixed it. It is actually another issue since this happened also when using "`/`". Anyway, it is good you caught it. :)

**Comment by javila** [comment]
Hi, @Proektsoftbg!

As I said in my previous comment, I understand the way Calcpad evaluates the input of composite units and I wasn't complaining about it at all. I was "complaining" about the ambiguous output formatting.

I meant...

The output of line 6 in your examples makes pretty obvious that it's a force divided by an acceleration. However, I think line 1 output is not that clear, since its output resembles line 3 one. That's why I said it was a inline division output formatting issue. IMHO, sometimes inline divisions demand output parenthesis for further clarification. Just like you did here (it should be the same for composite units):

<img width="350" alt="Image" src="https://github.com/user-attachments/assets/dd3f7158-e282-4e04-ac02-48d6eb0fcb38" />

**Comment by Proektsoftbg** [comment]
How did you get this?

**Comment by Proektsoftbg** [comment]
Aha, I see. Now it makes more clear. Give me 10 minutes, please. :)

**Comment by javila** [comment]
I feel stupid now... I'm sorry, Ned. You're right. I was using the installed version and not the one I compiled from source code.

But... There is still an issue to address:

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/41e0693a-0a58-4fb8-ab4c-98cbfd63e56c" />

**Comment by Proektsoftbg** [comment]
I started to like the ÷ operator so much that I added a new // shortcode for easier inserting of ÷.
I found that the best results for more complex equations are achieved by mixing both / and ÷. operators, especially when you have composite units:

<img width="406" height="256" alt="Image" src="https://github.com/user-attachments/assets/fc055cd1-5595-489c-ad18-4e7882fe4cb2" />

What do you think?

**Comment by javila** [comment]
Hi, @Proektsoftbg!

Sorry for the late reply.

I wanted to to suggest exactly that double slash alias for the ÷ operator. However, I thought you were not going to like it and I just dropped my idea...

I liked your idea of using a smaller slash for composite units. And I understand why you said you don't like all those parentheses in every equation. I really do. I just wanted to make the output looks more like what my students would see in books:
 
<img width="650" alt="Image" src="https://github.com/user-attachments/assets/09367425-ab3f-4308-b58f-a9e4c3d331af" />
